POST http://localhost:8080/tag
Content-Type: application/json

{
"name":"animal"
}

###

POST http://localhost:8080/category
Content-Type: application/json

{
  "name":"with legs"
}

###

PUT http://localhost:8080/pet
Content-Type: application/json

{
  "category": {
    "id": 1
  },
  "name": "doggie",
  "tags": [
    {
      "id": 0
    }
  ,
    {
      "id": 1
    }
  ],
  "status": "SOLD"
}


###
POST http://localhost:8080/pet
Content-Type: application/json

{
  "category": {
    "id": 0
  },
  "name": "dmkkk",
  "tags": [
    {
      "id": 0
    }
    ,
    {
      "id": 1
    }
  ],
  "status": "AVAILABLE"
}

###

GET http://localhost:8080/pet/findByStatus?status=AVAILABLE

###


GET http://localhost:8080/pet/9

###

DELETE http://localhost:8080/pet/0

######################################################################################################################

POST http://localhost:8080/store/order
Content-Type: application/json

{
  "petId": 1,
  "quantity": 0,
  "shipDate": "2021-02-24T11:39:34.739Z",
  "status": "APPROVED",
  "complete": true
}
###

GET http://localhost:8080/store/order/1

###

DELETE http://localhost:8080/store/order/1

###

GET http://localhost:8080/store/inventory

######################################################################################################################


POST http://localhost:8080/user
Content-Type: application/json

{
  "username": "Filipok",
  "firstName": "Filip",
  "lastName": "Durex",
  "email": "golova@gmail.com",
  "password": "samec",
  "phone": "+375296969696",
  "userStatus": 1
}

###

POST http://localhost:8080/user/createWithArray
Content-Type: application/json

[
  {
    "username": "Filipok",
    "firstName": "Filip",
    "lastName": "Durex",
    "email": "golovaTitana@gmail.com",
    "password": "samec",
    "phone": "+375296969696",
    "userStatus": 1
  },
  {
    "username": "sac",
    "firstName": "Kirill",
    "lastName": "Sev",
    "email": "maile@gmail.com",
    "password": "amlknvjb9",
    "phone": "+375290000000",
    "userStatus": 0
  }
]

###

POST http://localhost:8080/user/createWithList
Content-Type: application/json

[
  {
    "username": "Filipok",
    "firstName": "Filip",
    "lastName": "Durex",
    "email": "golovaTitana@gmail.com",
    "password": "samec",
    "phone": "+375296969696",
    "userStatus": 1
  },
  {
    "username": "sac",
    "firstName": "Kirill",
    "lastName": "Sev",
    "email": "maile@gmail.com",
    "password": "amlknvjb9",
    "phone": "+375290000000",
    "userStatus": 0
  }
]


###


GET http://localhost:8080/user/update


###

PUT http://localhost:8080/user/Filipok
Content-Type: application/json

{
  "username": "update",
  "firstName": "update",
  "lastName": "update",
  "email": "update",
  "password": "update",
  "phone": "update",
  "userStatus": 99
}

###

DELETE http://localhost:8080/user/update